### ISSUE TITLE
Reliable wheelchair accessibility

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Schedule_Best-Practices#32]
I'd like to add a best practice that makes sure somebody using a wheelchair or other assistive device is not directed towards a path that isn't safe for them to navigate.  This may involve a set of recommendations such as:

1. Defaulting to not accessible stops/stations
2. Stations that are accessible and include multiple boarding areas/stops within a parent station should be described using GTFS-Pathways

**Comment by scmcca** [comment]
This also feels like an implementation question depending on local standards of "accessibility". GTFS-Pathways describes things like width, slope and pathway mode for the purpose of local adjustment depending on whatever the standard is for "accessible". 

With this in mind, what should the recommendation be? For consumers would this be something like: If accessible pathway options are available, provide these as a clear option in the UI.

Thoughts?

**Comment by e-lo** [comment]
I really like your thinking about this from both a data side and UI side.  I would suggest:

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
