### ISSUE TITLE
Proposed best practice: Include tts_stop_name when stop name is potentially unintelligible using TTS technology

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Schedule_Best-Practices#34]

**Comment by barbeau** [comment]
I agree. Also, what is "potentially unintelligible" for a TTS engine isn't always obvious, so I would also suggest include specific examples as well. GTFS spec includes a few currently in the TTS field definition.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
