### ISSUE TITLE
Also reference in-seat (block) transfers recommendation under trips.txt?

### ISSUE THREAD

**Issue by antrim** [MobilityData/GTFS_Schedule_Best-Practices#4]
via @smsm1 - Shaun McDonald

"I'm surprised about the location of the following recommendation being within the transfers section only. Could it also be mentioned under trips.txt under the field block_id, which was where I was originally looking for the information. "

> 5 | If in-seat (block) transfers are allowed between trips, then the last stop of the arriving trip must be the same as the first stop of the departing trip.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
