### ISSUE TITLE
Versioning cadence

### ISSUE THREAD

**Issue by scmcca** [MobilityData/GTFS_Schedule_Best-Practices#41]
What does everyone think about specifying a cadence of versioning to the GTFS Best Practices (both Schedule and Realtime) that batches successful proposals over the last defined period into a single semantic versioning increment increase? This would help parties and products who use the GTFS Best Practices to plan updates to new releases, contracts, etc. Does a 6-month cadence sound reasonable? Shorter, longer?

**Comment by e-lo** [comment]
Next question: is this separate repo for BP (and versioning of them) the long-term BP solution? or are they all going to get put into the spec itself as "SHOULD" statements? 

If that is happening in the (relatively) near term, then we probably don't need to worry too much about the cadence being too frequent and should accept and upwards-version relatively frequently (monthly).

**Comment by barbeau** [comment]
My understanding is that this repo is effectively a short-term solution and that medium-to-long term solution is spec RFC2119 compliance and migrating these best practices as SHOULDs into spec, but I don't know what the timeframes are for "short", "medium", and "long".

**Comment by scmcca** [comment]
Strategies may evolve, but the current strategy is that the MobilityData BP repos are a short term solution for adding BP documentation. As we know, the work is underway to update GTFS Schedule to RFC 2119 ([#277](https://github.com/google/transit/pull/277)), with GTFS Realtime to follow. Following the updates to RFC 2119, we will work on voting in BP into the spec as "SHOULD"s (long-term solution).

All this being said, I agree with the proposed monthly cadence.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
