### ISSUE TITLE
Proposed Need: Articulating "redirects" from merged feeds

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Schedule_Best-Practices#43]
As proposed by @antrim - but as of now without consensus [ or a leading contender ] for a solution:

Example use case:

> Duarte Transit routes were absorbed into Foothill Transit (and published in Foothill’s feed). How to note?

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
