### ISSUE TITLE
Proposed Best Practice: Update practice for publishing future service

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Schedule_Best-Practices#48]
📝 This falls under the category of: *we (Cal-ITP) know this is an issue where there is great confusion and many practices* but don't 100% know what the best practice *should* be....although I can verify that the current published best-practice is out-of-date and insufficient. 

## Current Relevant Best Practice 

> One GTFS dataset should contain current and upcoming service (sometimes called a “merged” dataset). Google transitfeed tool's [merge function](https://github.com/google/transitfeed/wiki/Merge) can be used to create a merged dataset from two different GTFS feeds.
> - At any time, the published GTFS dataset should be valid for at least the next 7 days, and ideally for as long as the operator is confident that the schedule will continue to be operated.
> - If possible, the GTFS dataset should cover at least the next 30 days of service.

## Needs

1. **Reference currently relevant tools**:  the [`transitfeeds`](https://github.com/google/transitfeed) library has (pretty much, mostly) been deprecated and we shouldn't have a best practice which references it or encourages agencies to use it to solve this issue. 
2. **Accommodate large feeds**: Some agencies with very large and complex feeds  have been asked by some GTFS consumers to split their feed in two because of its size - just for a single `service_id`.  Adding multiple `service_id`s  would likely overwhelm their system.  Additionally, many feeds hosted using github infrastructure require files < 100MB and adding duplicate `service_id`s would surpass this.  
3. **Don't risk validation of currently-posted feed**: *One* of the main reasons for posting future service in advance is to make sure that any issues/problems with the future service data is identified in advance.  Posting (relatively) untested data within the same feed risks rendering the whole feed invalid. While this might not be as big of an issue for the large consumers who consume the data on a specific schedule, it isn't friendly to the accessibility of the feed overall.  This could also be especially important as agencies work on adding new features/attributes to their feed or update their business processes for dataset production. 

## Solutions Considered

Continue to suggest a merged feed with difference `service_id` s for:

- datasets which don't add new fields/features or dramatically new services, either of which might risk validation of the dataset containing current service. 
- small/medium feeds which would produce merged datasets < XXX Mb ? (not sure what this number should be?). 

? Are there current/relevant tools for merging datasets with all current attributes/files?

Otherwise, we've suggested the use of a separate permalink URL for future service.  For example Los Angeles Metro publishes their “future-service” feed to a different Git “branch” enabling a permalink download at [`https://gitlab.com/LACMTA/gtfs_bus/-/blob/future-service/gtfs_bus.zip`](https://gitlab.com/LACMTA/gtfs_bus/-/blob/future-service/gtfs_bus.zip)

---

Thoughts here? 

 @gcamp @Cristhian-HA @scmcca @westontrillium and others!

**Comment by barbeau** [comment]
>Are there current/relevant tools for merging datasets with all current attributes/files?

[onebusaway-gtfs-modules](https://github.com/OneBusAway/onebusaway-gtfs-modules) has a [merge command](http://developer.onebusaway.org/modules/onebusaway-gtfs-modules/current/onebusaway-gtfs-merge-cli.html)

**Comment by paulswartz** [comment]
@mbta uses https://github.com/mrcagney/gtfs_kit for merging.

**Comment by e-lo** [comment]
I'm curious what data consumers *need* for their pipelines w.r.t. future service? 

We have heard wide-spanning comments from transit providers "hearing from data consumers" that they should do a wide variety of things including:

1. Take a valid/current feed down before it expires in order to post a 'next week' feed at the feed permalink but...
   👎 This means the current feed is not accessible  

2. Produce a combined feed, which is ok if you are comfortable wrangling code or subscribe to various services but...
   👎 generally not feasible to the average transit agency  
   👎 can cause whole feed to catastrophically fail if new gtfs isn't appropriately validated 
   👎 not generally appropriate for introducing new "features" in your dataset

We have many transit providers asking questions about how they are supposed to doing things given mounting conflicting recommendations and we'd really like to make sure we can give them clear advice.

Consumers - Can you elaborate on your needs? (please flag others who should be flagged!)

@gcamp @jsteelz ?
@flocsy ?
@aababilov ?
@saraemarcus ?

**Comment by flocsy** [comment]
There are a few things to consider:

We usually load only a given number of days of future data, so even if the files already have the data for x-mas today that won't be used now.

The same policy dictates how we deal with changes: when we knew that the whole fare system will be changed on 1st Jan, or any kind of future change we produced both the old and new data in such a way that they could be loaded at the same time. This is also important for testing everything in advance BTW. So already in November we were able to generate the data and test it (or even to add new features that we needed for the change) and if we loaded let's say 10 days of future data, then we would start to load the new data on 21st Dec already into production. The way we do is identical to having both the current and the future data in one file.

But all this is already possible with the services.txt, calendar.txt in gtfs V1, so it might be that either I misunderstood the question or that I am not aware of some complications that you know of. Maybe you could explain why it might not be feasible and give some examples.

**Comment by e-lo** [comment]
> But all this is already possible with the services.txt, calendar.txt

Understood.  This is not a deficiency in the spec so much as a publishing practice.  Here are a few examples that we know about where things fall apart:

1. Agencies with large #s of stops and multiple service patterns in any given week approach (memory?) limits in various software (on consumer - at least from what they have heard - and sometimes the producer the software writing it out).  
2. (a special case of 1) Agencies that use GitHub to publish or manage large feeds approach their 100MB limit for `stop_times.txt` when publishing multiple service patterns.  
3. Some software that helps providers create and publish GTFS do not support multiple calendars/service patterns.  This is extremely common and tends to occur for agencies which don't have a lot of additional technical support/expertise – meaning they aren't going to spin up OBA.

Given that none of the above are likely to change/shift anytime soon (for more than a handful of agencies, at least), I think we need to have clear advice for them about how to make sure their schedules are appropriately represented to their customers.

Agencies with the problems above have tried to meet the best practices using a variety of methods including:
a. take the current feed down and publish the future feed at the "current feed permalink".  This meets the "permalink" recommendation but fails in having a current feed  with current service posted.
b. posting the future feed to a separate link
c. splitting their feed across services

**Comment by flocsy** [comment]
1. As I wrote, we as consumers do load only a few days of data,  it's a decision product made, I think it's more of a $$$ thing than tech thing in this case.
2. I don't know how to comment on this, I would think there are other tools to use, maybe even for free, and I would also think that it should not be very expensive for an agency to pay for a bigger storage nowadays. Also this might not be the way to do it in github, but the files (all the gtfs together) can be zipped to reduce the size.
3. I don't know these tools.

a. I think this is not a good solution. Consumers scan for the permanent url-s and when a change is detected they probably assume it's an update (and not that it's a continuation of the data that was there previously)
b. can work, but it is not that simple. Because if the only reason to cut the data into 2 is file size, and the ID-s used in the 2 files are OK (the same ID means the same thing) then it's easy for a consumer to concatenate (merge) them. However if the 2 files were created with a software not prepared for this, that produces conflicting ID-s in the 2 files then this is a nightmare for a consumer: they'll need a sophisticated algorithm to detect which ID in the 2 files should be treated as identical and which ID-s that are "accidentally" identical should be treated as different...
c. this could work, but probably can have 1 downfall: I guess transfers between services will become not possible to represent

**Comment by paulswartz** [comment]
@e-lo 
> (a special case of 1) Agencies that use GitHub to publish or manage large feeds approach their 100MB limit for `stop_times.txt` when publishing multiple service patterns.

GitHub (and presumably other Git hosting such as GitLab) supports [Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) which supports files up to 2GB on the Free plan.

**Comment by doconnoronca** [comment]
There are several major agencies that use option 2, including the Toronto TTC and New York MTA, so many consumers should be able to handle it. You can provide an archive of past files in case some new wants to start up after the future schedule has been released.

**Comment by willcanderson** [comment]
@doconnoronca I had thought that MTA follows an upcoming-only workflow, [based on this](https://new.mta.info/developers/gtfs-schedules-transition):

> For subways and buses, we replace the old schedule with the new one about a week before the new schedule goes into affect. Automated consumers have historically had challenges around the transition. Apps sometimes show the new schedule prematurely, or say that some routes aren't running.

When I looked at their [GTFS Schedule files](http://web.mta.info/developers/developer-data-terms.html#data) recently, they weren't using feed_info.txt.

Is there a different source of MTA schedule data that combines current and upcoming that sets feed_info.feed_start_date to the start of the upcoming schedule? If I could point to someone else doing it, that would certainly put a thumb on the scale for that option.

**Comment by doconnoronca** [comment]
Using the feed_info.txt would mean you are being more responsible then they are, since we have to rely on the dates in the calendar.txt file for them.

**Comment by willcanderson** [comment]
Further thoughts on my Option 2 above, where current and upcoming schedules are combined and `feed_info.feed_start_date` is set to the beginning of the upcoming service, when `trip_id` values begin match values in the RT feeds:

The [feed_info.txt spec](https://gtfs.org/schedule/reference/#feed_infotxt) says:

> It is recommended that dataset providers give schedule data outside this period [`feed_start_date` to `feed_end_date`] to advise of likely future service, but dataset consumers should treat it mindful of its non-authoritative status.

So it's blessed behavior to include service information that extends past `feed_end_date`. But what about including service information that occurs before `feed_start_date`?

My hope would be that data consumers would understand that info to be a fallback option, to be used in the event they don't already have the schedule cached, but with the drawback that the `trip_id` values won't match. Is this an avenue worth exploring? It would let us have one canonical permalink for all schedule information but always keep `trip_id` values matching real-time sources for all consumers who have the previous schedule cached and who honor `feed_info.feed_start_date`.

**Comment by doconnoronca** [comment]
Sorry, I misunderstood what you meant in Option 2. Publishing trip_ids that don't match real time values is not a good idea. Option 3 is the one that is similar to what the TTC and MTA does, except they don't have a link for current schedules. They have one link which is updates to the future schedule a while before it comes into effect. Having two links gives the consumer the flexibility to choose if they want the upcoming schedule early or not. Having both link to the same file at times shouldn't be a problem.

**Comment by derhuerst** [comment]
I think we're discussing at least two things in parallel here, so I'll split my response into two sections.

---

> The issue we're having stems from the fact that it's not feasible for us to create new `trip_id` values for minor schedule revisions.

Just to clarify there isn't another solution:
Are those schedule revisions large-scale & long-term enough to warrant adapting the schedule feeds? Would using a `TripUpdate` with `trip_update.trip.schedule_relationship: ADDED` work instead?

> Publishing trip_ids that don't match real time values is not a good idea.

Strongly agree! We should really try to keep the data quality as good as possible, and design our processes around this goal.

Making a GTFS(-RT) feed less expressive or consumable for the sake of circumventing technical limitations by specific software is a red flag to me. Would it be possible to assist the relevant software vendors to improve their GTFS processing, so that they can handle larger feeds?

(I'm someone who frequently works with uncomfortably large GTFS datasets, but I'm not "subjected" to software that I can't change that fails with large datasets, so my perspective might be different from yours.)

If it is not possible to get all consumers to handle a large but valid feed (😥), I propose to create a simplified/split-up feed for these consumers specifically, and keep the "general" feed as-is. I'd assume that problems with large feeds occur especially with larger transit districts/authorities, which usually have better tools & skills to do this.

---

Regarding the other problem discussed here: How should future schedule data be published which

1. might be formally invalid (e.g. CSV syntax errors, column names with typos)
2. might be inconsistent and/or wrong (formally valid, but not in line with the spec and/or to be flagged by validators)
3. might change frequently until it is in a "comitted-upon" (e.g. printed on a station board) shap?

I think that formally invalid datasets (1.) should not be published under any production URL. We have GTFS validators with GUIs to let even less tech-savvy transit authorities identify those errors. We could add a note that publishers can provide an additional "nightly" feed, which would be subject to problems at any time.

IMO publishing inconsistent (2.) but formally valid data would be an acceptable trade-off *only outside of of the `feed_{start,end}_date` time frame*. We could consider alleviating error-level validator rules to be only warning-level outside of this time frame.

With respect to changing data (3.), I think it is acceptable (whenever it is technically necessary, otherwise let's recommend unique & immutable IDs!) to use arbitrary IDs, even those that have been used in previous revisions of a dataset for different routes, as long as they have never been used within a) the `feed_{start,end}_date` time frame of a (production) schedule, and/or b) a GTFS-RT feed.

My general approach here is:
- Any ID within `feed_{start,end}_date` and/or GTFS-RT should be considered "stable".
	- I can use the ID to later receive realtime updates, e.g. if it has been cancelled
	- I can let clients store it as a reference to the trip/stop/etc., e.g. when bookmarking as a favourite line
	- I can use it as the key of the item it references.
- All other data is considered to be "beta-quality", with the goal of getting as much attention by consumers as possible, so that feedback about data quality issues can be given early, but not causing user-facing annoyances (e.g. alerts about reduced service, subpar routing because of missing data).

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
