### ISSUE TITLE
Update Best Practices with additional transfer types

### ISSUE THREAD

**Issue by isabelle-dr** [MobilityData/GTFS_Schedule_Best-Practices#51]
https://github.com/google/transit/pull/303 adds two transfer types (4 and 5).
The Best Practices section about transfers.txt should be modified to reflect this change.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
