### ISSUE TITLE
Should stop locations be required to be unique?

### ISSUE THREAD

**Issue by antrim** [MobilityData/GTFS_Schedule_Best-Practices#6]
I don't believe there is any requirement in the GTFS core or GTFS Best Practices that specifies two stop records (in same dataset) should not overlap, though this is a warning in feed_validator.py. Should we add this best practice or requirement?

**Comment by barbeau** [comment]
I would say it would be a good best practice, as most instances I've seen of this have been errors in data. This is probably a good candidate for the group to review, though, to make sure we aren't missing anything.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
