### ISSUE TITLE
calendar.txt and stop_id as stop_code

### ISSUE THREAD

**Issue by RideSchedules** [MobilityData/GTFS_Schedule_Best-Practices#7]
Regarding the GTFS best practices, looks like you left out two common mistakes:

1. stop_code should be included even if used as stop_id (since there is no way to tell stop_id is actually stop_code).
2. calendar.txt entries should not overlap for a specific day and multiple entries for the same general service (Weekday, Weekend, etc) should be date continuous.  (Otherwise, referencing service timetables becomes nonsense).

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
